CREATE TABLE PRODUCT (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CODE VARCHAR(256) NOT NULL
    NAME VARCHAR(256) NOT NULL,
    DESCRIPTION TEXT NOT NULL
);

CREATE TABLE PRODUCT_PRICE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    AMOUNT DECIMAL(30,30) NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    STATUS VARCHAR(256) NOT NULL
);
