DROP TABLE PRODUCT;
DROP TABLE PRODUCT_PRICE;
DROP TABLE BOARD_GAME;



CREATE TABLE PRODUCT (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CODE VARCHAR(256) NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    PRODUCT_TYPE VARCHAR(256) NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    STATUS VARCHAR(256) NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL,
    LASTMODIFIED_ON TIMESTAMP NOT NULL,
    VERSION BIGINT
);


CREATE TABLE BOARD_GAME (
    ID BIGINT NOT NULL,
    NUMBER_OF_PLAYERS INT NOT NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE BOARD_GAME ADD FOREIGN KEY (ID) REFERENCES PRODUCT(ID);

CREATE TABLE BRICK (
    ID BIGINT NOT NULL,
    HEIGHT INT NOT NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE BRICK ADD FOREIGN KEY (ID) REFERENCES PRODUCT(ID);



CREATE TABLE PRODUCT_PRICE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    AMOUNT DECIMAL(30,30) NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    STATUS VARCHAR(256) NOT NULL
);
